[project]
name = "langchain-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.10",
    "langchain-anthropic>=1.3.3",
    "langchain-classic>=1.0.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.12",
    "langchain-openai>=1.1.9",
    "langchain-tavily>=0.2.17",
    "python-dotenv>=1.2.1",
]
